services:
    nginx:
      image: nginx:alpine
      container_name: nginx-sub
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - ./config/subscribe:/etc/nginx/subscribe:ro
        - ./logs/nginx:/var/log/nginx

    ssserver:
      image: ghcr.io/shadowsocks/ssserver-rust:latest
      container_name: ssserver
      restart: always
      ports:
        - "8388:8388/tcp"
        - "8388:8388/udp"
      volumes:
        - ./config/config.json:/etc/shadowsocks-rust/config.json:ro
      environment:
        RUST_LOG: trace
      logging:
        driver: json-file
        options:
          max-size: "10m"
          max-file: "5"