#!/bin/sh
set -e

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$ROOT_DIR"

XRAY_IMAGE_DEFAULT=ghcr.io/xtls/xray-core@sha256:592ec4d11f656db95598d01e76dbcc6e002d67360b96a5436500a938230f52c7
NODE_NAME_ARG=
SERVER_ADDR_ARG=
XRAY_PORT_ARG=443
FORCE=0
ENABLE_BBR=0
SKIP_DOCKER_INSTALL=0

usage() {
    cat <<'EOF'
Usage:
  ./deploy.sh --node Singapore --addr 1.2.3.4.sslip.io [options]

Options:
  --node NAME             Node name shown in subscriptions, for example Singapore.
  --addr HOST             Public host or IP used by clients and subscription URLs.
  --port PORT             Public VLESS REALITY port. Default: 443.
  --force                 Regenerate .env even if it already exists.
  --enable-bbr            Enable host BBR tuning before starting containers.
  --skip-docker-install   Fail if Docker is missing instead of trying to install it.
  -h, --help              Show this help.

If .env already exists, deploy.sh keeps it by default and only regenerates runtime
config plus containers. Use --force when deploying a fresh node config.
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --node)
            NODE_NAME_ARG=${2:-}
            shift 2
            ;;
        --addr)
            SERVER_ADDR_ARG=${2:-}
            shift 2
            ;;
        --port)
            XRAY_PORT_ARG=${2:-}
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        --enable-bbr)
            ENABLE_BBR=1
            shift
            ;;
        --skip-docker-install)
            SKIP_DOCKER_INSTALL=1
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Error: unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

need_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Error: required command not found: $1"
        exit 1
    fi
}

run_as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        echo "Error: root privileges are required for: $*"
        exit 1
    fi
}

install_docker() {
    if command -v docker >/dev/null 2>&1; then
        return
    fi

    if [ "$SKIP_DOCKER_INSTALL" -eq 1 ]; then
        echo "Error: Docker is not installed."
        exit 1
    fi

    if [ "$(uname -s)" != "Linux" ]; then
        echo "Error: Docker is missing. Please install Docker Desktop, then rerun ./deploy.sh."
        exit 1
    fi

    need_cmd curl
    echo "Docker not found. Installing Docker with get.docker.com..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    run_as_root sh /tmp/get-docker.sh
}

compose_cmd() {
    if docker compose version >/dev/null 2>&1; then
        echo "docker compose"
    elif command -v docker-compose >/dev/null 2>&1; then
        echo "docker-compose"
    else
        echo "Error: Docker Compose is not available." >&2
        exit 1
    fi
}

generate_xray_keys() {
    key_output=$(docker run --rm "$XRAY_IMAGE_DEFAULT" x25519)
    private_key=$(printf '%s\n' "$key_output" | awk -F': ' '/^Private[ _]?[Kk]ey:/ || /^PrivateKey:/ {print $2; exit}')
    public_key=$(printf '%s\n' "$key_output" | awk -F': ' '/^Public[ _]?[Kk]ey:/ || /^Password \(PublicKey\):/ {print $2; exit}')

    if [ -z "$private_key" ] || [ -z "$public_key" ]; then
        echo "Error: failed to generate Xray REALITY keys"
        printf '%s\n' "$key_output"
        exit 1
    fi
}

write_env() {
    if [ -f .env ] && [ "$FORCE" -ne 1 ]; then
        echo ".env already exists; keeping current node config."
        return
    fi

    if [ -z "$SERVER_ADDR_ARG" ]; then
        echo "Error: --addr is required when generating .env"
        exit 1
    fi
    if [ -z "$NODE_NAME_ARG" ]; then
        NODE_NAME_ARG=Node
    fi

    need_cmd openssl
    generate_xray_keys

    admin_secret=$(openssl rand -hex 32)
    short_id=$(openssl rand -hex 8)

    umask 077
    cat > .env <<EOF
# Public host used in subscription URLs and VLESS/Clash server fields.
# Use your node domain here, not the raw server IP, if clients should connect by domain.
SERVER_ADDR=${SERVER_ADDR_ARG}
NODE_NAME=${NODE_NAME_ARG}
ADMIN_SECRET=${admin_secret}
NGINX_CONF=nginx.conf

# Public VLESS REALITY port.
XRAY_IMAGE=${XRAY_IMAGE_DEFAULT}
XRAY_PORT=${XRAY_PORT_ARG}
XRAY_API_ADDR=xray:10085
XRAY_INBOUND_TAG=vless-in
XRAY_FULL_SYNC_INTERVAL=10m

# Generated by ./deploy.sh
XRAY_PRIVATE_KEY=${private_key}
XRAY_PUBLIC_KEY=${public_key}
XRAY_SHORT_ID=${short_id}

# A real TLS site used by REALITY. Keep SERVER_NAME aligned with DEST host.
XRAY_SERVER_NAME=www.cloudflare.com
XRAY_DEST=www.cloudflare.com:443
EOF
    echo "Generated .env for ${NODE_NAME_ARG} (${SERVER_ADDR_ARG})."
}

install_docker
need_cmd openssl

if [ "$ENABLE_BBR" -eq 1 ]; then
    run_as_root ./scripts/enable-bbr.sh
fi

write_env
./scripts/setup.sh

COMPOSE=$(compose_cmd)
$COMPOSE up -d --build

echo ""
echo "Deployment complete."
$COMPOSE ps

. ./.env
echo ""
echo "Admin UI: http://${SERVER_ADDR}/"
echo "Proxy:    ${SERVER_ADDR}:${XRAY_PORT:-443} (${NODE_NAME:-Node})"
echo "Login with ADMIN_SECRET from .env"
