server {
    listen 8080;

    sendfile off;
    access_log /var/log/nginx/access.log;

    location /sub/f18c843ba46a14a220efc197350179f0/ {
        root /etc/nginx;
        rewrite ^/sub/f18c843ba46a14a220efc197350179f0/(.*)$ /subscribe/$1 break;
        autoindex off;
        default_type application/octet-stream;
        add_header Content-Disposition 'attachment; filename="clash.yaml"' always;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
        add_header X-Content-Type-Options "nosniff" always;
    }

    location / {
        return 404;
    }
}
