server {
    listen 80;
    server_name _;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    access_log off;

    location /sub/ {
        access_log /var/log/nginx/sub.access.log;
        proxy_pass http://subserver:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://subserver:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Admin-Secret $http_x_admin_secret;
    }

    location / {
        root /etc/nginx/web;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
