server {
    listen 80;
    server_name tokyo-node.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name tokyo-node.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/tokyo-node.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tokyo-node.duckdns.org/privkey.pem;

    sendfile off;
    access_log /var/log/nginx/access.log;

    location /sub/f18c843ba46a14a220efc197350179f0/ {
        root /etc/nginx;
        rewrite ^/sub/f18c843ba46a14a220efc197350179f0/(.*)$ /subscribe/$1 break;
        autoindex off;
        default_type application/octet-stream;
        add_header Content-Disposition 'attachment; filename="clash.yaml"' always;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
        add_header X-Content-Type-Options "nosniff" always;
    }

    location / {
        return 404;
    }
}
