mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:
  - name: Tokyo
    type: ss
    server: 38.47.105.9
    port: 8388
    cipher: aes-256-gcm
    password: "wHWJNebP6TE90lu1tLIsFQZurLOzln8rAWmT/L48JSA="
    udp: true

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Tokyo
      - DIRECT

rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
