version = 5.6.0
archive_dir = /etc/letsencrypt/archive/tokyo-node.duckdns.org
cert = /etc/letsencrypt/live/tokyo-node.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/tokyo-node.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/tokyo-node.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/tokyo-node.duckdns.org/fullchain.pem
[renewalparams]
account = f36978fb3aac570b63e71cb7439dc8e6
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
tokyo-node.duckdns.org = /var/www/certbot
